### ISSUE TITLE
Incorporation into the core library

### ISSUE THREAD

**Issue by zanieb** [rpeden/prefect-multiprocess#3]
Did you know we wanted to add this into the core library? I just found about this project! What's the status of it?

**Comment by rpeden** [comment]
No, I didn't realize that. It worked well last time I tried it, but it's fairly primitive. It spins up a bunch of processes; each process runs one task at a time before picking up another. 

I probably still have some fancier versions of it on my dev laptop that use `concurrent.futures` or anyio worker processes instead of plain `multiprocessing`, but IIRC they didn't make much difference and broke output streaming. 

I think I set this aside because there was a failing test I wasn't sure how to fix. But given what I've learned about Prefect since November, I can probably resolve it now. I'll give it a try either later this week or on the weekend.

**Comment by madkinsz** [comment]
I would hold off on it until I finish refactoring concurrency handling — I think there will be some necessary changes to the task runners and I've already implemented a process worker pools that may be helpful.
